### ISSUE TITLE
The tutorial seems very outdated. Is everything being used still supported?

### ISSUE THREAD

**Issue by madki** [googlecodelabs/cast-unity-plugin#10]
Some of the steps in the tutorial seem outdated. I'm trying to used the plugin with unity 5.6 and android sdk 26.0.0+

The steps mentioned to add playservices seem to be very old. Are there plans to update the codelab? Where can I find help for achieving the same objective as the codelab's tutorial does.

**Comment by LeonNicholls** [comment]
We are working on an update. Here is the main documentation for the plugin: https://developers.google.com/cast/docs/remote_unity
