### ISSUE TITLE
Problem with appcompat when compiling for Android

### ISSUE THREAD

**Issue by varumora-everywoah** [googlecodelabs/cast-unity-plugin#11]
I'm using Unity 2018.1.0f2 and when trying to compile for Android I always get this error:

Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.Light.ActionButton'.
Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.ActionButton'.

I've also tried with Unity 2017 without any luck.

**Comment by LeonNicholls** [comment]
Support for this plugin has been deprecated.
