### ISSUE TITLE
No SFX when gun fires

### ISSUE THREAD

**Issue by jrgrafton** [googlecodelabs/cast-unity-plugin#2]
Assume this may have been intentionally removed?

**Comment by jrgrafton** [comment]
Seems as though there's still some references to it:

Assets/Scripts/Player/PlayerShooting.cs(19,21): warning CS0414: The private field `CompleteProject.PlayerShooting.gunAudio' is assigned but its value is never used

**Comment by LeonNicholls** [comment]
Yes, intentionally removed. This is an issue for the sample and not the codelab. Since this is not an error, will likely keep as is since I don't want to touch the original Unity source code unless neccessary.
