### ISSUE TITLE
";MOBILE_INPUT" keeps getting removed from "Scripting Define Symbols" whenever project is run or saved

### ISSUE THREAD

**Issue by jrgrafton** [googlecodelabs/cast-unity-plugin#6]
5.2.3f1 - you need to press enter to save.
(http://forum.unity3d.com/threads/global-defines-in-unity-4.170866/)

May be worth mentioning in docs.

**Comment by LeonNicholls** [comment]
Added text to explicitly press enter to save value. Will be part of next published version.
