### ISSUE TITLE
Step 12 refers to "MenuCanvas/PausePanel/PauseButton Button OnClick" at the end however PauseButton should be nested under MenuCanvas otherwise it doesn't show

### ISSUE THREAD

**Issue by jrgrafton** [googlecodelabs/cast-unity-plugin#7]
Step 12 refers to "MenuCanvas/PausePanel/PauseButton Button OnClick" at the end however PauseButton should be nested under MenuCanvas otherwise it doesn't show

It's referred to correctly at the start of Step 12 "Use the Unity editor menu GameObject > UI > Button options to add a button to MenuCanvas."

**Comment by LeonNicholls** [comment]
Fixed. Will be part of next published version.
