### ISSUE TITLE
Unable to find devices

### ISSUE THREAD

**Issue by pertinate** [googlecodelabs/cast-unity-plugin#9]
I recently got the plugin to work on my phone (was having troubles with the cast button even showing up) and now I'm having trouble with the app finding my chromecast. I know it's not my chromecast because other apps (E.G. youtube) can find and connect to it. So am I doing something wrong?

**Comment by LeonNicholls** [comment]
Apps like YouTube have additional discovery protocols beyond Cast. Please try one of our mobile sample apps to confirm if there is a Cast discovery issue.

**Comment by pertinate** [comment]
Hi I did try the app provided by the YouTube guide and it still didn't
work.

**Comment by LeonNicholls** [comment]
You have to use one of your sample apps, not YouTube to confirm that discovery works. Also double check the serial number of chromecast device is registered in your Google Cast Developer Console.
